name: Python CI

# Trigger the workflow on any push to the main branch or pull request 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest #container name

    steps:
    #step1: pre-build action to checkout the code from the repo (version2)
    - name: Checkout code
      uses: actions/checkout@v2
        
    #step2: setup python env
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    #step3: Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #step4: Run Tests
    - name: Run Tests
      run: pytest
    
